# Generated by Django 3.1.4 on 2020-12-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Fname', models.CharField(max_length=200)),
                ('C_Lname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=500)),
                ('prix', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoApp.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoApp.produit')),
            ],
        ),
    ]
